import React, {
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo
} from 'react';
import { createRoot } from 'react-dom/client';
import { CommunitySection, CommunityAdminSection } from './community.jsx';

/* ---------- Config ---------- */

const repoUrl = 'https://github.com/lucianvaleblackthorn/my-gpt-2';
const rawBase = 'https://raw.githubusercontent.com/lucianvaleblackthorn/my-gpt-2/main';
const casesJsonUrl = `${rawBase}/data/cases.json`;
const styleLibraryJsonUrl = `${rawBase}/data/style-library.json`;
const supabaseUrl = window.__ENV__?.VITE_SUPABASE_URL || '';
const supabaseAnonKey = window.__ENV__?.VITE_SUPABASE_ANON_KEY || '';

/* ---------- Copy ---------- */

const copy = {
  en: {
    loading: 'Loading GPT-Image2 cases...',
    brand: 'GPT-Image2 Gallery',
    navCases: 'Cases',
    navSkill: 'Skill',
    navTemplates: 'Templates',
    navCommunity: 'Community',
    navSponsor: 'API',
    navMembership: 'Membership',
    communityQrAlt: 'GPT-Image2 WeChat community group invitation',
    eyebrow: 'Real-time updated GPT-Image2 prompt gallery',
    title: 'From viral images to reusable prompts.',
    subtitle:
      'A visual workbench for GPT-Image2 creation: browse real cases, copy prompts, test image generation online, explore industrial-grade templates, and join the creator community.',
    explore: 'Browse Cases',
    githubProject: 'GitHub Project',
    sponsorProject: 'API',
    sponsorProjectLabel: 'Open APIMart API',
    cases: 'cases',
    categories: 'categories',
    templates: 'templates',
    sectionEyebrow: 'Copy, filter, reuse',
    sectionTitle: 'Viral cases and prompts, one click away.',
    templateEyebrow: '20+ industrial-grade prompt templates',
    templateTitle: 'Start with mature templates, then remix from the case library.',
    templateSubtitle:
      'Each template is distilled from real GPT-Image2 cases, including structure, constraints, and pitfall guidance, suitable for direct reuse in production workflows.',
    templateKind: 'Prompt Templates',
    openTemplate: 'Open Template',
    skillEyebrow: 'Agent Skill',
    skillTitle: 'Install the GPT-Image2 style library into Claude Code and Codex.',
    skillSubtitle:
      'Install a skill that lets your agent auto-select from templates, styles, scenes, and pitfall rules sourced from this site, and directly output copyable GPT-Image2 prompts.',
    skillCommandLabel: 'Install to Local Agent',
    skillPromptLabel: 'Try this request',
    skillPrompt: 'Use the gpt-image-2-style-library skill to generate a city life system map',
    skillCopyCommand: 'Copy Command',
    skillOpenDocs: 'Open skill source',
    skillNpm: 'View npm package',
    skillCopied: 'Command copied',
    skillExampleAlt: 'City life system map generated using the GPT-Image2 style library skill',
    skillExampleCaption: 'Example: Generate a city life system atlas using gpt-image-2-style-library.',
    skillStats: ['Claude Code ready', 'Codex ready', '20+ templates'],
    search: 'Search cases, sources, prompts...',
    category: 'Category',
    style: 'Style',
    scene: 'Scene',
    all: 'All',
    matching: 'matching cases',
    openGithub: 'Open GitHub project',
    copied: 'Copied',
    copyPrompt: 'Copy Prompt',
    copyTemplatePrompt: 'Copy Template',
    favorite: 'Favorite',
    favorited: 'Favorited',
    unfavorite: 'Unfavorite',
    myFavorites: 'My Favorites',
    noFavorites: 'No favorite cases yet.',
    signInToFavorite: 'Sign in to favorite cases.',
    favoriteSaved: 'Added to favorites.',
    favoriteRemoved: 'Removed from favorites.',
    favoriteFailed: 'Failed to update favorites, please try again later.',
    closePreview: 'Close preview',
    viewDetails: 'Details',
    generateTest: 'Generate Test',
    generateImage: 'Generate Image',
    generating: 'Generating...',
    editablePrompt: 'Editable Prompt',
    generatedResult: 'Generated Result',
    originalImage: 'Original Image',
    savedInBrowser: 'Saved in this browser',
    resetPrompt: 'Reset Prompt',
    oneFreeGeneration: '1 free test image',
    superAdminGeneration: 'Super admin mode: each generation costs 1 credit.',
    generationCost: '1 credit consumed',
    freeLimitReached: 'Free quota exhausted. Purchase credit packs or subscribe to continue.',
    creditsRequired: 'Insufficient credits. Purchase credit packs or subscribe to continue.',
    generationBusy: 'Generation service is busy, please try again later.',
    generationFailed: 'Generation failed, please try again later.',
    promptRequired: 'Prompt cannot be empty and must not exceed 6000 characters.',
    serverUnavailable: 'Generation service is not yet configured.',
    checkoutUnavailable: 'Payment feature is not yet configured.',
    checkoutFailed: 'Failed to create payment, please try again later.',
    billingSuccess: 'Payment is being processed. Credits will be added automatically after Stripe confirmation.',
    billingCancelled: 'Payment cancelled. You can choose a different credit pack or membership plan anytime.',
    alipayReturnPending: 'Returned from Alipay, querying order result via server...',
    alipayPaymentSuccess: 'Alipay payment confirmed, credits have been added.',
    alipayPaymentPending: 'Alipay result not yet confirmed. Please do not pay again. Refreshing this page will continue querying the same order.',
    alipayQueryFailed: 'Unable to confirm Alipay result temporarily. Please do not pay again. Refresh this page or contact support.',
    authRequired: 'Sign in to generate test images.',
    signIn: 'Sign In',
    signInTitle: 'Sign in to generate test images',
    signInSubtitle: 'Sign in with Google or Watcha to unlock test generation, credits, and membership.',
    authRateLimited: 'Too many sign-in attempts, please try again later.',
    googleNotConfigured: 'Google sign-in is not yet enabled.',
    continueWithGoogle: 'Continue with Google',
    continueWithWatcha: 'Continue with Watcha',
    authNotConfigured: 'Authentication is not yet configured.',
    watchaNotConfigured: 'Watcha sign-in is not yet configured.',
    watchaSessionExpired: 'Watcha session has expired, please try again.',
    watchaDenied: 'Watcha authorization cancelled.',
    watchaLoginFailed: 'Watcha sign-in failed, please try again later.',
    authError: 'Sign-in failed, please try again later.',
    signOut: 'Sign Out',
    account: 'Account',
    accountSettings: 'Account Settings',
    accountTitle: 'Account Settings',
    accountSubtitle: 'Manage your display name, membership status, and GPT-Image2 credit usage.',
    displayName: 'Display Name',
    saveProfile: 'Save Profile',
    profileSaved: 'Profile saved.',
    profileUpdateFailed: 'Failed to save profile, please try again later.',
    googleAvatarSource: 'Avatar syncs with your sign-in account.',
    accountOverview: 'Account Overview',
    totalGenerations: 'Total Generations',
    totalGenerationCredits: 'Credits Used',
    generationUsage: 'Generation Usage',
    openCase: 'View Case',
    sourceCase: 'Related Case',
    noGenerationTransactions: 'No generation history yet.',
    adminPanel: 'Admin Panel',
    membershipCenter: 'Membership & Credits',
    superAdmin: 'Super admin',
    credits: 'Credits',
    buyCredits: 'Buy Credits',
    subscribe: 'Subscribe',
    manageSubscription: 'Manage Subscription',
    currentPlan: 'Current Plan',
    noPlan: 'Free User',
    activeUntil: 'Active until',
    membershipPlans: 'Membership Plans',
    creditPacks: 'Credit Packs',
    monthlyCredits: (count) => `${count} credits / month`,
    packCredits: (count) => `${count} credits`,
    billingTitle: 'Membership & credits',
    billingSubtitle: 'Members get monthly credits. Credit packs can be added anytime for more GPT-Image2 tests.',
    balanceTitle: 'Current balance',
    transactionHistory: 'Credit history',
    noTransactions: 'No credit history yet.',
    loadBilling: 'Loading billing...',
    openBilling: 'Open membership center',
    paymentReady: 'Secure checkout via Stripe or Alipay.',
    billingNotReady: 'No payment provider is configured yet.',
    payWithStripe: 'Stripe',
    payWithAlipay: 'Alipay',
    alipayPriceMissing: 'Alipay price pending',
    adminAdjust: 'Adjust credits',
    creditAmount: 'Amount',
    reason: 'Reason',
    applyAdjustment: 'Apply adjustment',
    freeReady: 'Free test ready',
    freeUsedShort: 'Free test used',
    signInToGenerate: 'Sign in to generate',
    creditsAvailable: (count) => `${count} credit${count === 1 ? '' : 's'} available`,
    adminTitle: 'User admin',
    adminSubtitle: 'Traffic, users, memberships, credits, and generation activity in one dashboard.',
    adminMetrics: 'Dashboard',
    trafficMetrics: 'Traffic',
    businessMetrics: 'Business',
    analyticsNotConfigured: 'GA4 is not configured yet. Business metrics are still available.',
    analyticsLoadFailed: 'GA4 data could not be loaded. Business metrics are still available.',
    invalidDateRange: 'Choose a date range within 180 days.',
    rangeToday: 'Today',
    range7d: '7 days',
    range30d: '30 days',
    range90d: '90 days',
    customRange: 'Custom',
    startDate: 'Start date',
    endDate: 'End date',
    applyRange: 'Apply',
    selectedRange: 'Selected range',
    pv: 'PV',
    uv: 'UV',
    visits: 'Visits',
    sessions: 'Sessions',
    newUsers: 'New users',
    registeredUsers: 'Registered users',
    newRegistrations: 'New registrations',
    newMembers: 'New members',
    activeMemberships: 'Active members',
    totalGenerationsMetric: 'Total generations',
    rangeGenerations: 'Range generations',
    succeeded: 'Succeeded',
    failed: 'Failed',
    pending: 'Pending',
    creditsConsumed: 'Credits consumed',
    creditsInCirculation: 'Credits in balances',
    purchasedCredits: 'Purchased credits',
    membershipCredits: 'Membership credits',
    dailyTraffic: 'Daily traffic',
    trafficTrend: 'Traffic trend',
    businessTrend: 'Business trend',
    registrations: 'Registrations',
    topPages: 'Top pages',
    channels: 'Channels',
    countries: 'Countries',
    pageViews: 'Views',
    noAnalyticsRows: 'No analytics rows yet.',
    refresh: 'Refresh',
    users: 'Users',
    role: 'Role',
    creditBalance: 'Credits',
    freeGeneration: 'Free test',
    spentCredits: 'Spent',
    purchased: 'Purchased',
    lastGeneration: 'Last generation',
    createdAt: 'Created',
    loadingUsers: 'Loading users...',
    noUsers: 'No users yet.',
    adminOnly: 'Only super admins can view this page.',
    fullPrompt: 'Full Prompt',
    templatePrompt: 'Template Prompt',
    useWhen: 'Use When',
    guidance: 'Guidance',
    pitfalls: 'Pitfalls',
    examples: 'Example Cases',
    source: 'Source',
    openOnGithub: 'Open on GitHub',
    limit: (count) => `Showing the first ${count} results for speed. Use search or filters to narrow the gallery.`
  },
  zh: {
    loading: 'Loading GPT-Image2 cases...',
    brand: 'GPT-Image2 Gallery',
    navCases: 'Cases',
    navSkill: 'Skill',
    navTemplates: 'Templates',
    navCommunity: 'Community',
    navSponsor: 'API',
    navMembership: 'Membership',
    communityQrAlt: 'GPT-Image2 WeChat community group invitation',
    eyebrow: 'Real-time updated GPT-Image2 prompt gallery',
    title: 'From viral images to reusable prompts.',
    subtitle:
      'A visual workbench for GPT-Image2 creation: browse real cases, copy prompts, test image generation online, explore industrial-grade templates, and join the creator community.',
    explore: 'Browse Cases',
    githubProject: 'GitHub Project',
    sponsorProject: 'API',
    sponsorProjectLabel: 'Open APIMart API',
    cases: 'cases',
    categories: 'categories',
    templates: 'templates',
    sectionEyebrow: 'Copy, filter, reuse',
    sectionTitle: 'Viral cases and prompts, one click away.',
    templateEyebrow: '20+ industrial-grade prompt templates',
    templateTitle: 'Start with mature templates, then remix from the case library.',
    templateSubtitle:
      'Each template is distilled from real GPT-Image2 cases, including structure, constraints, and pitfall guidance, suitable for direct reuse in production workflows.',
    templateKind: 'Prompt Templates',
    openTemplate: 'Open Template',
    skillEyebrow: 'Agent Skill',
    skillTitle: 'Install the GPT-Image2 style library into Claude Code and Codex.',
    skillSubtitle:
      'Install a skill that lets your agent auto-select from templates, styles, scenes, and pitfall rules sourced from this site, and directly output copyable GPT-Image2 prompts.',
    skillCommandLabel: 'Install to Local Agent',
    skillPromptLabel: 'Try this request',
    skillPrompt: 'Use the gpt-image-2-style-library skill to generate a city life system map',
    skillCopyCommand: 'Copy Command',
    skillOpenDocs: 'Open skill source',
    skillNpm: 'View npm package',
    skillCopied: 'Command copied',
    skillExampleAlt: 'City life system map generated using the GPT-Image2 style library skill',
    skillExampleCaption: 'Example: Generate a city life system atlas using gpt-image-2-style-library.',
    skillStats: ['Claude Code ready', 'Codex ready', '20+ templates'],
    search: 'Search cases, sources, prompts...',
    category: 'Category',
    style: 'Style',
    scene: 'Scene',
    all: 'All',
    matching: 'matching cases',
    openGithub: 'Open GitHub project',
    copied: 'Copied',
    copyPrompt: 'Copy Prompt',
    copyTemplatePrompt: 'Copy Template',
    favorite: 'Favorite',
    favorited: 'Favorited',
    unfavorite: 'Unfavorite',
    myFavorites: 'My Favorites',
    noFavorites: 'No favorite cases yet.',
    signInToFavorite: 'Sign in to favorite cases.',
    favoriteSaved: 'Added to favorites.',
    favoriteRemoved: 'Removed from favorites.',
    favoriteFailed: 'Failed to update favorites, please try again later.',
    closePreview: 'Close preview',
    viewDetails: 'Details',
    generateTest: 'Generate Test',
    generateImage: 'Generate Image',
    generating: 'Generating...',
    editablePrompt: 'Editable Prompt',
    generatedResult: 'Generated Result',
    originalImage: 'Original Image',
    savedInBrowser: 'Saved in this browser',
    resetPrompt: 'Reset Prompt',
    oneFreeGeneration: '1 free test image',
    superAdminGeneration: 'Super admin mode: each generation costs 1 credit.',
    generationCost: '1 credit consumed',
    freeLimitReached: 'Free quota exhausted. Purchase credit packs or subscribe to continue.',
    creditsRequired: 'Insufficient credits. Purchase credit packs or subscribe to continue.',
    generationBusy: 'Generation service is busy, please try again later.',
    generationFailed: 'Generation failed, please try again later.',
    promptRequired: 'Prompt cannot be empty and must not exceed 6000 characters.',
    serverUnavailable: 'Generation service is not yet configured.',
    checkoutUnavailable: 'Payment feature is not yet configured.',
    checkoutFailed: 'Failed to create payment, please try again later.',
    billingSuccess: 'Payment is being processed. Credits will be added automatically after Stripe confirmation.',
    billingCancelled: 'Payment cancelled. You can choose a different credit pack or membership plan anytime.',
    alipayReturnPending: 'Returned from Alipay, querying order result via server...',
    alipayPaymentSuccess: 'Alipay payment confirmed, credits have been added.',
    alipayPaymentPending: 'Alipay result not yet confirmed. Please do not pay again. Refreshing this page will continue querying the same order.',
    alipayQueryFailed: 'Unable to confirm Alipay result temporarily. Please do not pay again. Refresh this page or contact support.',
    authRequired: 'Sign in to generate test images.',
    signIn: 'Sign In',
    signInTitle: 'Sign in to generate test images',
    signInSubtitle: 'Sign in with Google or Watcha to unlock test generation, credits, and membership.',
    authRateLimited: 'Too many sign-in attempts, please try again later.',
    googleNotConfigured: 'Google sign-in is not yet enabled.',
    continueWithGoogle: 'Continue with Google',
    continueWithWatcha: 'Continue with Watcha',
    authNotConfigured: 'Authentication is not yet configured.',
    watchaNotConfigured: 'Watcha sign-in is not yet configured.',
    watchaSessionExpired: 'Watcha session has expired, please try again.',
    watchaDenied: 'Watcha authorization cancelled.',
    watchaLoginFailed: 'Watcha sign-in failed, please try again later.',
    authError: 'Sign-in failed, please try again later.',
    signOut: 'Sign Out',
    account: 'Account',
    accountSettings: 'Account Settings',
    accountTitle: 'Account Settings',
    accountSubtitle: 'Manage your display name, membership status, and GPT-Image2 credit usage.',
    displayName: 'Display Name',
    saveProfile: 'Save Profile',
    profileSaved: 'Profile saved.',
    profileUpdateFailed: 'Failed to save profile, please try again later.',
    googleAvatarSource: 'Avatar syncs with your sign-in account.',
    accountOverview: 'Account Overview',
    totalGenerations: 'Total Generations',
    totalGenerationCredits: 'Credits Used',
    generationUsage: 'Generation Usage',
    openCase: 'View Case',
    sourceCase: 'Related Case',
    noGenerationTransactions: 'No generation history yet.',
    adminPanel: 'Admin Panel',
    membershipCenter: 'Membership & Credits',
    superAdmin: 'Super admin',
    credits: 'Credits',
    buyCredits: 'Buy Credits',
    subscribe: 'Subscribe',
    manageSubscription: 'Manage Subscription',
    currentPlan: 'Current Plan',
    noPlan: 'Free User',
    activeUntil: 'Active until',
    membershipPlans: 'Membership Plans',
    creditPacks: 'Credit Packs',
    monthlyCredits: (count) => `${count} credits / month`,
    packCredits: (count) => `${count} credits`,
    billingTitle: 'Membership & credits',
    billingSubtitle: 'Members get monthly credits. Credit packs can be added anytime for more GPT-Image2 tests.',
    balanceTitle: 'Current balance',
    transactionHistory: 'Credit history',
    noTransactions: 'No credit history yet.',
    loadBilling: 'Loading billing...',
    openBilling: 'Open membership center',
    paymentReady: 'Secure checkout via Stripe or Alipay.',
    billingNotReady: 'No payment provider is configured yet.',
    payWithStripe: 'Stripe',
    payWithAlipay: 'Alipay',
    alipayPriceMissing: 'Alipay price pending',
    adminAdjust: 'Adjust credits',
    creditAmount: 'Amount',
    reason: 'Reason',
    applyAdjustment: 'Apply adjustment',
    freeReady: 'Free test ready',
    freeUsedShort: 'Free test used',
    signInToGenerate: 'Sign in to generate',
    creditsAvailable: (count) => `${count} credit${count === 1 ? '' : 's'} available`,
    adminTitle: 'User admin',
    adminSubtitle: 'Traffic, users, memberships, credits, and generation activity in one dashboard.',
    adminMetrics: 'Dashboard',
    trafficMetrics: 'Traffic',
    businessMetrics: 'Business',
    analyticsNotConfigured: 'GA4 is not configured yet. Business metrics are still available.',
    analyticsLoadFailed: 'GA4 data could not be loaded. Business metrics are still available.',
    invalidDateRange: 'Choose a date range within 180 days.',
    rangeToday: 'Today',
    range7d: '7 days',
    range30d: '30 days',
    range90d: '90 days',
    customRange: 'Custom',
    startDate: 'Start date',
    endDate: 'End date',
    applyRange: 'Apply',
    selectedRange: 'Selected range',
    pv: 'PV',
    uv: 'UV',
    visits: 'Visits',
    sessions: 'Sessions',
    newUsers: 'New users',
    registeredUsers: 'Registered users',
    newRegistrations: 'New registrations',
    newMembers: 'New members',
    activeMemberships: 'Active members',
    totalGenerationsMetric: 'Total generations',
    rangeGenerations: 'Range generations',
    succeeded: 'Succeeded',
    failed: 'Failed',
    pending: 'Pending',
    creditsConsumed: 'Credits consumed',
    creditsInCirculation: 'Credits in balances',
    purchasedCredits: 'Purchased credits',
    membershipCredits: 'Membership credits',
    dailyTraffic: 'Daily traffic',
    trafficTrend: 'Traffic trend',
    businessTrend: 'Business trend',
    registrations: 'Registrations',
    topPages: 'Top pages',
    channels: 'Channels',
    countries: 'Countries',
    pageViews: 'Views',
    noAnalyticsRows: 'No analytics rows yet.',
    refresh: 'Refresh',
    users: 'Users',
    role: 'Role',
    creditBalance: 'Credits',
    freeGeneration: 'Free test',
    spentCredits: 'Spent',
    purchased: 'Purchased',
    lastGeneration: 'Last generation',
    createdAt: 'Created',
    loadingUsers: 'Loading users...',
    noUsers: 'No users yet.',
    adminOnly: 'Only super admins can view this page.',
    fullPrompt: 'Full Prompt',
    templatePrompt: 'Template Prompt',
    useWhen: 'Use When',
    guidance: 'Guidance',
    pitfalls: 'Pitfalls',
    examples: 'Example Cases',
    source: 'Source',
    openOnGithub: 'Open on GitHub',
    limit: (count) => `Showing the first ${count} results for speed. Use search or filters to narrow the gallery.`
  }
};

const labelMap = {
  zh: {
    'Architecture & Spaces': 'Architecture & Spaces',
    Architecture: 'Architecture',
    Brand: 'Brand',
    'Brand & Logos': 'Brand & Logos',
    Character: 'Character',
    Characters: 'Characters',
    'Characters & People': 'Characters & People',
    Charts: 'Charts',
    'Charts & Infographics': 'Charts & Infographics',
    Classical: 'Classical',
    Commerce: 'Commerce',
    Creative: 'Creative',
    Documents: 'Documents',
    'Documents & Publishing': 'Documents & Publishing',
    Education: 'Education',
    Fashion: 'Fashion',
    Food: 'Food',
    History: 'History',
    'History & Classical Themes': 'History & Classical Themes',
    Illustration: 'Illustration',
    'Illustration & Art': 'Illustration & Art',
    Infographic: 'Infographic',
    'Other Use Cases': 'Other Use Cases',
    Photography: 'Photography',
    'Photography & Realism': 'Photography & Realism',
    Poster: 'Poster',
    'Posters & Typography': 'Posters & Typography',
    Product: 'Product',
    Products: 'Products',
    'Products & E-commerce': 'Products & E-commerce',
    Realistic: 'Realistic',
    Scenes: 'Scenes',
    'Scenes & Storytelling': 'Scenes & Storytelling',
    Social: 'Social',
    Story: 'Story',
    Tech: 'Tech',
    Travel: 'Travel',
    UI: 'Interface',
    'UI & Interfaces': 'UI & Interfaces'
  }
};

function cx(...classes) {
  return classes.filter(Boolean).join(' ');
}

function textFor(value, language) {
  if (!value) return '';
  if (typeof value === 'string') return value;
  return value[language] || value.en || value.zh || '';
}

function listFor(value, language) {
  const localized = value?.[language] || value?.en || value?.zh || [];
  return Array.isArray(localized) ? localized : [];
}

function compactText(value, maxLength = 180) {
  if (!value || value.length